### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by jyounus** [onmyway133/Snowflake#1]
Hey there,

I've only been messing around with the example project and noticed that for some example files (Misc -> Christmas) it takes a second or two before it opens the next screen. It feels as if the simulator is frozen. 

Questions:
1. Does the reading of the data/rendering the file take place on a background thread? 
2. Can I use this lib from a background thread to not block the main thread?
3. Can I download SVG data from my backend and use it with this lib or does it currently only support SVGs that are bundled within the project?

A suggestion:
What do you think of making this work with a UIImageView using a category? Render the data like you're doing now, then rasterise the output into an image (maybe even cache it on disk at this point as a PNG/JPEG for quick access next time and less processing?) and display it in the imageView.  Not sure what sort of performance impact this would have, but it would make working with SVGs easier imo. 

Thanks!

**Comment by onmyway133** [comment]
@jyounus Hi, thanks for checking this out

- In the example projects, I include quite a lot of svg files to play around with. That `christmas` svg file is quite complex, and it takes sometime. This needs to be improved
- The parsing is done on the main thread, because I want to keep it simple. We can dispatch it to the background thread
- The `Document` is init with `Data`, so as long as you pass it `Data`, it is fine
- The basic idea is to convert svg elements into `CALayer`. And with this `CALayer` we can make a `UIView` with `Document.svg.view`, then we can capture this `UIView` as `UIImage` and scale it. Yeah, this convenience can be in the category

**Comment by jyounus** [comment]
> We can dispatch it to the background thread

So just to confirm, I shouldn't have any issues to do the following:

```
DispatchQueue.global(qos: .userInteractive).async() {
    guard let path = Bundle.main.path(forResource: "xmas", ofType: "svg"),
        let data = try? Data(contentsOf: URL(fileURLWithPath: path)),
        let document = Snowflake.Document(data: data)
        else { return }
    
    DispatchQueue.main.async {
        let view = document.svg.view(size: CGSize(width: 100, height: 100))
    }
}
```

Is that correct? I'm assuming since the last line is dealing with a View directly, it has to be on the main thread.

**Comment by onmyway133** [comment]
@jyounus that is correct. The `last line`, which is from `Shape` objects -> `UIView` needs to be on main queue

**Comment by jyounus** [comment]
Fair enough, thanks! I'll close this issue for now. :)
